### ISSUE TITLE
Pretrained model not available

### ISSUE THREAD

**Issue by andyyankai** [yinyunie/Total3DUnderstanding#43]
I try to use the link for pretrained model but showed 404. Is there any updated link or I missed something?

**Comment by yinyunie** [comment]
Thanks for your reminder,

I have fixed these links. Could you please check them again?

Best,
Yinyu

**Comment by SunWeiLin-Lynne** [comment]
Hello, have you downloaded the pre-trained weights？I still can't open this link.
